### ISSUE TITLE
Nova are incompatible with custom enchantments of EcoEnchant.

### ISSUE THREAD

**Issue by YYYork** [xenondevs/Nova#387] opened 2024-05-29 04:21 UTC
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16, git-Purpur-2176 (MC: 1.20.4)

### Nova Addons and Versions

Machines-0.4.5 Simple-Upgrades-1.3

### Expected behavior

compatible with Custom enchantments of EcoEnchant

### Observed/Actual behavior

Exception when trying to initialize vanilla enchantment categories

### Steps to reproduce

1.Place Nova-0.16.jar eco-6.70.1-all.jar EcoEnchants v12.6.0.jar in 'plugins' folder
2.Place Machines-0.4.5.jar Simple-Upgrades-1.3.jar in 'plugins/Nova/addons' folder
3.Run server

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/15478696/latest.log)

### Errors

```log
[12:19:16] [Server thread/INFO]: [Nova] Enabling Nova v0.16
[12:19:26] [Server thread/INFO]: [Nova] Extracting default config
[12:19:26] [Server thread/INFO]: [Nova] Registering packet handlers
[12:19:26] [Server thread/INFO]: [Nova] Loading Addons...
[12:19:26] [Server thread/INFO]: [Nova] [Machines] Loaded Machines [machines] v0.4.5
[12:19:26] [Server thread/INFO]: [Nova] [Simple-Upgrades] Loaded Simple-Upgrades [simple_upgrades] v1.3
[12:19:26] [Server thread/INFO]: [Nova] Applying patches...
[12:19:30] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:65) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / nova:enchantment]: ResourceKey[nova:enchantment / minecraft:excavation]
	at net.minecraft.core.Registry.getOrThrow(Registry.java:90) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at xyz.xenondevs.nova.util.NMSUtilsKt.getOrThrow(NMSUtils.kt:379) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.item.enchantment.Enchantment$Companion.of(Enchantment.kt:88) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategory.<init>(EnchantmentCategory.kt:107) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.register(VanillaEnchantmentCategories.kt:30) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.<clinit>(VanillaEnchantmentCategories.kt:26) ~[Nova-0.16.jar:?]
	... 17 more
[12:19:30] [Server thread/WARN]: [Nova] Shutting down the server...
```

**Comment by NichtStudioCode** [comment] 2024-05-29 07:44
Duplicate of #341

**Closed by NichtStudioCode** 2024-05-29 07:44 UTC
Labels: type: bug
