### ISSUE TITLE
[Request - Block] Electric Stone Cutter

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [xenondevs/Nova#43] opened 2021-10-15 20:14 UTC
### Potential name of the block

Electric Stone Cutter

### Describe the block

like a normal stone cutter but automated (More blocks for your money or something)

**Comment by NichtStudioCode** [comment] 2021-10-15 20:17
Duplicate of #31

**Closed by NichtStudioCode** 2021-10-15 20:17 UTC
Labels: new block

**Comment by XxMr1234GamerzxX** [comment] 2021-10-15 20:28
this is not duplicate of that 

for 3 reasons

this would allow not only for automation but better yields on recipes like 1 stone = 2 stone bricks (instead of 1) make the cost of running the block worth it 
 
 block with a purpose it only does stone materials (maybe add a wood cutting one on top of this to pair with the tree farm???? maybe?????) 
 
also it makes it so in your plugin there are is parity between vanilla blocks and your blocks there a electric alternatives for late game so it builds upon the vanilla game autocrafting is too generalised and is harder to implement and get correct (maybe OP), as this would just be a standalone block like any other machine in your plugin

**Comment by XxMr1234GamerzxX** [comment] 2021-12-03 14:45
@NichtStudioCode please reopen this as it not a duplicate for the above reason

**Comment by ByteZ1337** [comment] 2021-12-03 14:58
AutoCrafters will be able to interact with most vanilla crafting blocks, including the stone cutter. So a separate block isn't needed.
