### ISSUE TITLE
Compatibility issues between nova and ecoenchants

### ISSUE THREAD

**Issue by postyizhan** [xenondevs/Nova#398] opened 2024-07-12 18:00 UTC
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova:0.16.1,paper-1.20.4-497.jar

### Nova Addons and Versions

-

### Expected behavior

-

### Observed/Actual behavior

When nova is installed simultaneously with ecoenchants, nova will generate an error message and shut down the server

### Steps to reproduce

1.Install nova eco and ecoenchants
2.Start server

### Server log

https://mclo.gs/ZC2YVdS

<details>
<summary>details</summary>

```
[01:47:28] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:47:29] [ServerMain/INFO]: Loaded 1174 recipes
[01:47:29] [ServerMain/INFO]: Loaded 1271 advancements
[01:47:29] [Server thread/INFO]: Starting minecraft server version 1.20.4
[01:47:29] [Server thread/INFO]: Loading properties
[01:47:29] [Server thread/INFO]: This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
[01:47:30] [Server thread/INFO]: Server Ping Player Sample Count: 12
[01:47:30] [Server thread/INFO]: Using 4 threads for Netty based IO
[01:47:30] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[01:47:30] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[01:47:30] [Server thread/INFO]: Default game type: SURVIVAL
[01:47:30] [Server thread/INFO]: Generating keypair
[01:47:30] [Server thread/INFO]: Starting Minecraft server on *:25565
[01:47:30] [Server thread/INFO]: Using epoll channel type
[01:47:30] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:47:30] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[01:47:30] [Server thread/INFO]: [eco] Initializing eco
[01:47:31] [Server thread/INFO]: [Nova] Loading 2 libraries...
[01:47:31] [Server thread/INFO]: [Nova] Loaded library /run/media/postyizhan/Disk/MCserver/TEST/libraries/xyz/xenondevs/configurate/configurate-yaml/4.2.0-SNAPSHOT/configurate-yaml-4.2.0-SNAPSHOT.jar
[01:47:31] [Server thread/INFO]: [Nova] Loaded library /run/media/postyizhan/Disk/MCserver/TEST/libraries/xyz/xenondevs/configurate/configurate-core/4.2.0-SNAPSHOT/configurate-core-4.2.0-SNAPSHOT.jar
[01:47:31] [Server thread/INFO]: [Nova] Loaded library /run/media/postyizhan/Disk/MCserver/TEST/libraries/io/leangen/geantyref/geantyref/1.3.14/geantyref-1.3.14.jar
[01:47:31] [Server thread/INFO]: [Nova] Loaded library /run/media/postyizhan/Disk/MCserver/TEST/libraries/xyz/xenondevs/configurate/configurate-extra-kotlin/4.2.0-SNAPSHOT/configurate-extra-kotlin-4.2.0-SNAPSHOT.jar
[01:47:31] [Server thread/INFO]: [Nova] Loaded library /run/media/postyizhan/Disk/MCserver/TEST/libraries/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.20/kotlin-stdlib-common-1.8.20.jar
[01:47:31] [Server thread/INFO]: [EcoEnchants] Initializing EcoEnchants
[01:47:31] [Server thread/INFO]: [eco] Loading server plugin eco v6.71.5
[01:47:31] [Server thread/INFO]: [Nova] Loading server plugin Nova v0.16.1
[01:47:31] [Server thread/INFO]: [EcoEnchants] Loading server plugin EcoEnchants v12.12.0
[01:47:31] [Server thread/INFO]: [libreforge] Initializing libreforge
[01:47:31] [Server thread/INFO]: [libreforge] Loading server plugin libreforge v4.65.0
[01:47:31] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:47:31] [Server thread/INFO]: [eco] Enabling eco v6.71.5
[01:47:31] [Server thread/INFO]: [eco] Loading eco
[01:47:31] [Server thread/INFO]: [eco] Scanning for conflicts...
[01:47:31] [Server thread/INFO]: [eco] No conflicts found!
[01:47:31] [Server thread/INFO]: [Nova] Enabling Nova v0.16.1
[01:47:32] [Server thread/INFO]: [Nova] Extracting default config
[01:47:32] [Server thread/INFO]: [Nova] Registering packet handlers
[01:47:32] [Server thread/INFO]: [Nova] Loading Addons...
[01:47:32] [Server thread/INFO]: [Nova] [Deep-Storage] Loaded Deep-Storage [deep_storage] v1.6.0
[01:47:32] [Server thread/INFO]: [Nova] [Jetpacks] Loaded Jetpacks [jetpacks] v0.1.12
[01:47:32] [Server thread/INFO]: [Nova] [Logistics] Loaded Logistics [logistics] v0.2.8
[01:47:32] [Server thread/INFO]: [Nova] [Machines] Loaded Machines [machines] v0.4.5
[01:47:32] [Server thread/INFO]: [Nova] [Simple-Elevator] Loaded Simple-Elevator [simple_elevator] v2.0.0
[01:47:32] [Server thread/INFO]: [Nova] [Simple-Upgrades] Loaded Simple-Upgrades [simple_upgrades] v1.3
[01:47:32] [Server thread/INFO]: [Nova] [Vanilla-Hammers] Loaded Vanilla-Hammers [vanilla_hammers] v1.4
[01:47:32] [Server thread/INFO]: [Nova] Applying patches...
[01:47:35] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:65) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / nova:enchantment]: ResourceKey[nova:enchantment / minecraft:cubism]
	at net.minecraft.core.Registry.getOrThrow(Registry.java:90) ~[paper-1.20.4.jar:git-Paper-497]
	at xyz.xenondevs.nova.util.NMSUtilsKt.getOrThrow(NMSUtils.kt:379) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.Enchantment$Companion.of(Enchantment.kt:88) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategory.<init>(EnchantmentCategory.kt:107) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.register(VanillaEnchantmentCategories.kt:30) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.<clinit>(VanillaEnchantmentCategories.kt:26) ~[Nova-0.16.1.jar:?]
	... 17 more
[01:47:35] [Server thread/WARN]: [Nova] Shutting down the server...
[01:47:35] [Server thread/INFO]: [EcoEnchants] Enabling EcoEnchants v12.12.0
[01:47:35] [Server thread/INFO]: [EcoEnchants] Loading EcoEnchants
[01:47:35] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[01:47:35] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[01:47:35] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[01:47:35] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[01:47:35] [Server thread/INFO]: Preparing level "world"
[01:47:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[01:47:37] [Server thread/INFO]: Time elapsed: 725 ms
[01:47:37] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[01:47:37] [Server thread/INFO]: Time elapsed: 44 ms
[01:47:37] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[01:47:37] [Server thread/INFO]: Time elapsed: 31 ms
[01:47:37] [Server thread/INFO]: [libreforge] Enabling libreforge v4.65.0
[01:47:37] [Server thread/INFO]: [libreforge] Loading libreforge
[01:47:37] [Server thread/INFO]: [libreforge] 
[01:47:37] [Server thread/INFO]: [libreforge] Hey, what's this plugin doing here? I didn't install it!
[01:47:37] [Server thread/INFO]: [libreforge] libreforge is the effects system for plugins like EcoEnchants,
[01:47:37] [Server thread/INFO]: [libreforge] EcoJobs, EcoItems, etc. If you're looking for config options for
[01:47:37] [Server thread/INFO]: [libreforge] things like cooldown messages, lrcdb, and stuff like that, you'll
[01:47:37] [Server thread/INFO]: [libreforge] find it under /plugins/libreforge
[01:47:37] [Server thread/INFO]: [libreforge] 
[01:47:37] [Server thread/INFO]: [libreforge] Don't worry about updating libreforge, it's handled automatically!
[01:47:37] [Server thread/INFO]: [libreforge] 
[01:47:37] [Server thread/WARN]: [Nova] Skipping post world initialization
[01:47:37] [Server thread/INFO]: Running delayed init tasks
[01:47:38] [Server thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:47:38] [Server thread/INFO]: Done (8.341s)! For help, type "help"
[01:47:38] [Server thread/INFO]: Stopping server
[01:47:38] [Server thread/INFO]: [libreforge] Disabling libreforge v4.65.0
[01:47:38] [Server thread/INFO]: [libreforge] Cleaning up...
[01:47:38] [Server thread/INFO]: [EcoEnchants] Disabling EcoEnchants v12.12.0
[01:47:38] [Server thread/INFO]: [EcoEnchants] Cleaning up...
[01:47:38] [Server thread/INFO]: [Nova] Disabling Nova v0.16.1
[01:47:38] [Server thread/INFO]: [eco] Disabling eco v6.71.5
[01:47:38] [Server thread/INFO]: [eco] Saving player data...
[01:47:38] [Server thread/INFO]: [eco] Saved player data! Took 1ms
[01:47:38] [Server thread/INFO]: [eco] Cleaning up...
[01:47:39] [Server thread/INFO]: Saving players
[01:47:39] [Server thread/INFO]: Saving worlds
[01:47:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[01:47:40] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[01:47:40] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[01:47:40] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[01:47:40] [Server thread/INFO]: [ChunkHolderManager] Saved 118 block chunks, 118 entity chunks, 0 poi chunks in world 'world' in 0.26s
[01:47:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[01:47:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Saved 5 block chunks, 5 entity chunks, 0 poi chunks in world 'world_nether' in 0.01s
[01:47:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[01:47:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[01:47:41] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_the_end' in 0.00s
[01:47:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[01:47:41] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[01:47:41] [Server thread/INFO]: Flushing Chunk IO
[01:47:41] [Server thread/INFO]: Closing Thread Pool
[01:47:41] [Server thread/INFO]: Closing Server
```

</details>

### Errors

```log
https://mclo.gs/e2mhtYL

[01:47:35] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:65) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / nova:enchantment]: ResourceKey[nova:enchantment / minecraft:cubism]
	at net.minecraft.core.Registry.getOrThrow(Registry.java:90) ~[paper-1.20.4.jar:git-Paper-497]
	at xyz.xenondevs.nova.util.NMSUtilsKt.getOrThrow(NMSUtils.kt:379) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.Enchantment$Companion.of(Enchantment.kt:88) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategory.<init>(EnchantmentCategory.kt:107) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.register(VanillaEnchantmentCategories.kt:30) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.<clinit>(VanillaEnchantmentCategories.kt:26) ~[Nova-0.16.1.jar:?]
	... 17 more
[01:47:35] [Server thread/WARN]: [Nova] Shutting down the server...
```

### Additional context

-

**Comment by ByteZ1337** [comment] 2024-07-12 18:02
Duplicate of #341

**Closed by ByteZ1337** 2024-07-12 18:02 UTC
Labels: type: bug
