### ISSUE TITLE
[Bug] Wireless charger really laggy

### ISSUE THREAD

**Issue by Ielelele29** [xenondevs/Nova#22] opened 2021-08-15 11:23 UTC
**Plugin Version and Server Software**
Minecraft server verison: git-Paper-90 (1.17.1)
Plugin version: 0.4.1

**Describe the bug**
Wireless charger is very laggy (with 20 wireless charger places the server from from 20 to 3 tps)

**To Reproduce**
1. Place some wireless charger
2. Get lag

**Errors**
No error in console

**Screenshot**
![image](https://user-images.githubusercontent.com/76882886/129476810-332b0349-bda9-41e5-9c3c-847515f229d5.png)

**Additional context**
These are the timings: https://timings.aikar.co/?id=8f7d28e44ba54ab58d9a02d6824abdef

**Comment by ByteZ1337** [comment] 2021-08-29 12:58
The lag seems to be fixed in the upcoming 0.5 update. It was probably caused by the old ItemStack.novaMaterial implementation: https://github.com/xenondevs/Nova/blob/278374d9f763e451f8eda4f78c8d22f74d8c5a69/src/main/kotlin/xyz/xenondevs/nova/util/MaterialUtils.kt#L29-L37
So it wasn't directly caused by the wireless charger. However, the wireless chargers' implementation is still poor, so it'll probably be improved as well.

**Closed** 2021-08-29 13:14 UTC
Labels: bug
