### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Medic0525** [xenondevs/Nova#111] opened 2022-03-01 10:29 UTC
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova:0.8.5 Spigot:3436-spigot-699290c-1e87776

### Observed/Actual behavior

duplicating any items in the plugin

### Steps to reproduce

1. check the type of the item is, there are 3 types in nova plugin items, structure void, shulker shell and barrier
2. throw the decoy items which will be turned into the thing you wanted to duplicate(has to be same type as the thing you want to dupe)
3. throw the thing that you want to dupe

### Additional context

So far as I know that v0.8.6 did not fix any dupe related bug so I think it still works in it

**Comment by NichtStudioCode** [comment] 2022-03-01 22:08
Did you actually try this without any other plugins on the server?

**Comment by NichtStudioCode** [comment] 2022-03-05 14:23
Closing this issue because this most likely caused by another plugin and the author doesn't respond.

**Closed by NichtStudioCode** 2022-03-05 14:23 UTC
Labels: type: bug
