### ISSUE TITLE
[Bug] sometimes when the server restarts it breaks every nova block and causes people to have to replace it everytime

### ISSUE THREAD

**Issue by McLOVINandCo** [xenondevs/Nova#15] opened 2021-07-12 19:32 UTC
its not at spawn or anything sometimes it doesnt break sometimes it does one time my friends worked while mine broke so everytime we have to replace it using the debug commands we were able to remove the broken entites but it still kept happening without being able to do anything about it

**Comment by NichtStudioCode** [comment] 2021-07-12 19:44
Duplicate of #13

**Closed by NichtStudioCode** 2021-07-12 19:44 UTC
Labels: bug, duplicate
