### ISSUE TITLE
Server startup error

### ISSUE THREAD

**Issue by Agriosz97** [xenondevs/Nova#547] opened 2024-12-27 13:51 UTC
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.18 alpha 11, paper-1.21.4-53, 1.21.4

### Nova Addons and Versions

Nova

### Observed/Actual behavior

I think I installed everything correctly. It worked with old versions, but the server with version 1.21.4 is impossible to start for me. Essentially, the server won't start.

### Steps to reproduce

After installing nova 0.18 alpha.11 the server just won't start. there are no other plugins, all server settings are basic.

### Server log

[14:35:59] [ServerMain/INFO]: [bootstrap] Running Java 23 (Java HotSpot(TM) 64-Bit Server VM 23.0.1+11-39; Oracle Corporation null) on Windows 11 10.0 (amd64)
[14:35:59] [ServerMain/INFO]: [bootstrap] Loading Paper 1.21.4-53-main@326c687 (2024-12-27T12:59:10Z) for Minecraft 1.21.4
[14:36:00] [ServerMain/INFO]: [PluginInitializerManager] Initializing plugins...
[14:36:02] [ServerMain/INFO]: [PluginInitializerManager] Initialized 1 plugin
[14:36:02] [ServerMain/INFO]: [PluginInitializerManager] Paper plugins (1):
 - Nova (0.18-alpha.11)
[14:36:03] [ServerMain/INFO]: [Nova] Applying patches...
[14:36:03] [ServerMain/ERROR]: [Nova] 
xyz.xenondevs.nova.patch.PatcherException: 
    JDK: 23.0.1 by Oracle Corporation
    JVM: Java HotSpot(TM) 64-Bit Server VM, 23.0.1+11-39 by Oracle Corporation
    Operating system: Windows 11, amd64
    Startup parameters: [--add-modules=jdk.incubator.vector, -XX:MaxRAMPercentage=95.0, -Dfile.encoding=UTF-8, -Xms128M, -Xmx8192M, -XX:+PerfDisableSharedMem, -XX:+ParallelRefProcEnabled, -XX:+UnlockExperimentalVMOptions, -XX:+DisableExplicitGC, -XX:-OmitStackTraceInFastThrow, -XX:+AlwaysPreTouch, -XX:MaxGCPauseMillis=100, -XX:G1NewSizePercent=30, -XX:G1MaxNewSizePercent=40, -XX:G1HeapRegionSize=8M, -XX:G1ReservePercent=20, -XX:G1HeapWastePercent=5, -XX:G1MixedGCCountTarget=4, -XX:InitiatingHeapOccupancyPercent=15, -XX:G1MixedGCLiveThresholdPercent=90, -XX:G1RSetUpdatingPauseTimePercent=5, -XX:SurvivorRatio=32, -XX:MaxTenuringThreshold=1, -Dusing.aikars.flags=true, -Daikars.new.flags=true]

	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.run(Patcher.kt:81) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.NovaBootstrapper.init(NovaBootstrapper.kt:104) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.NovaBootstrapper.bootstrap(NovaBootstrapper.kt:82) ~[Nova-0.18-alpha.11.jar:?]
	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:36) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:24) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:30) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:46) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at net.minecraft.server.Main.main(Main.java:112) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ca/spottedleaf/moonrise/common/util/ChunkSystem
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.impl.chunk.ChunkSchedulingPatch.<init>(ChunkSchedulingPatch.kt:29) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.impl.chunk.ChunkSchedulingPatch.<clinit>(ChunkSchedulingPatch.kt) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.transformers_delegate$lambda$0(Patcher.kt:59) ~[Nova-0.18-alpha.11.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.getTransformers(Patcher.kt:53) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.runTransformers(Patcher.kt:117) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.run(Patcher.kt:77) ~[Nova-0.18-alpha.11.jar:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: ca.spottedleaf.moonrise.common.util.ChunkSystem
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.21.4.jar:1.21.4-53-326c687]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.impl.chunk.ChunkSchedulingPatch.<init>(ChunkSchedulingPatch.kt:29) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.impl.chunk.ChunkSchedulingPatch.<clinit>(ChunkSchedulingPatch.kt) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.transformers_delegate$lambda$0(Patcher.kt:59) ~[Nova-0.18-alpha.11.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.getTransformers(Patcher.kt:53) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.runTransformers(Patcher.kt:117) ~[Nova-0.18-alpha.11.jar:?]
	at Nova-0.18-alpha.11.jar/xyz.xenondevs.nova.patch.Patcher.run(Patcher.kt:77) ~[Nova-0.18-alpha.11.jar:?]
	... 14 more

**Comment by ByteZ1337** [comment] 2024-12-27 13:59
Duplicate of #546

**Closed by ByteZ1337** 2024-12-27 13:59 UTC
Labels: type: bug
