### ISSUE TITLE
Getting "Internal Exception: NBT tag that was too big" and getting kicked from server, unable to rejoin without restart

### ISSUE THREAD

**Issue by micchu129** [xenondevs/Nova#286] opened 2023-10-03 04:57 UTC
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.14.10, Paper: git-Paper-196

### Nova Addons and Versions

Logistics v0.2.6, Machines v0.4.3, Jetpacks v0.1.10, Simple Upgrades v1.1, Vanilla Hammers v1.2

### Expected behavior

Not getting removed from server, and at least be able to rejoin successfully. 
Usual occurs in jetpack flight, though occasionally non flight. 

### Observed/Actual behavior

Getting kicked from server mid flight, client returns a:
`Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097315 bytes where max allowed: 2097152` 
Error has occurred to all players at least once. Once kicked, that specific player is unable to rejoin server until server restart

### Steps to reproduce

1. Sprint to flight
2. Fly around
3. crashes on non specific locations/heights though most often when going to chunks outside of base. 

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/12788677/latest.log)

### Errors

```log
NBT error did not output in console, but did show up on kick message in player client: 
`Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097315 bytes where max allowed: 2097152`
```

### Additional context

Started this server about a month and a half ago. Everything was smooth for the first few weeks. Started experiencing random kicks, took out some plugins to troubleshoot. Experienced a resourcepack issue yesterday which I fixed through patreon hosting (is resourcepack.host down?) taking the opportunity to remove all other plugins but nova to trouble shoot, but still getting kicked.

**Comment by micchu129** [comment] 2023-10-03 15:56
Kick occurred again, this time no flight. 
Just jumping around in my underground base mining. 
Was mining using quarry, but quarry has been stopped already, nothing obvious to me as to why I was getting kicked.
Confirming I was unable to rejoin server after kick, just gets kicked off immediately after joining. 
Attaching server logs again: 
[latest.log](https://github.com/xenondevs/Nova/files/12794470/latest.log)

**Comment by wordandahalf** [comment] 2023-10-10 15:43
I also have encountered this issue with a basic custom addon that just adds blocks and items.

**Comment by ShanMan123** [comment] 2024-01-06 08:08
Any updates on regards this issue? I'm having the same issue as well.

**Comment by ByteZ1337** [comment] 2024-02-02 11:12
Should be fixed in the next patch

**Closed** 2024-02-02 11:12 UTC
Labels: type: bug

**Comment by AllayBreeze** [comment] 2024-03-09 08:37
I met this on 0.16-alpha.3, when I put a leather helmet into my inventory. I rejoined server after deleted my player data files, but can't reproduce it again. 
I can provide the playerdata causing this issue (if it can help testing):
[21977ad6-e9c6-3151-9b67-4d6f5008e4fe.zip](https://github.com/xenondevs/Nova/files/14545682/21977ad6-e9c6-3151-9b67-4d6f5008e4fe.zip)
