### ISSUE TITLE
[Bug] Nova causes server threads to freeze

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#174] opened 2022-09-09 06:51 UTC
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova Version: 0.10.6;git-petal-"eb64b15" (MC: 1.19.2)*

### Nova Addons and Versions

Jetpacks-0.1.3 Logistics-0.1.2 Machines-0.1.6

### Expected behavior

[latest.log](https://github.com/xenondevs/Nova/files/9536000/latest.log)

### Observed/Actual behavior

Nothing in game

### Steps to reproduce

1. Start server
2. Wait for it

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/9536001/latest.log)

**Comment by NichtStudioCode** [comment] 2022-09-09 15:01
Duplicate of #170

**Closed** 2022-09-09 15:01 UTC
Labels: type: bug, resolution: duplicate
