### ISSUE TITLE
[Bug] Mob Killer doesnt work

### ISSUE THREAD

**Issue by BlackGrandStyle** [xenondevs/Nova#53] opened 2021-11-06 22:50 UTC
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.6.11 / Purpur 1415

### Observed/Actual behavior

mob killer doesn't work under all conditions
regardless of whether it is in the region or not

### Steps to reproduce

1. Place and setup Mob Killer
2. Enjoy

### Errors

https://imgur.com/a/hEcr3nw

**Comment by NichtStudioCode** [comment] 2021-11-07 11:11
Works fine for me.
You're using an outdated Purpur version (even though you checked the box that it's not), so I am closing the issue. I don't know if that's the cause, but I am not willing to check for problems on outdated server versions.
If it's not caused by the outdated version, you're probably leaving out important information again.
A screenshot is not an error.

**Closed by NichtStudioCode** 2021-11-07 11:11 UTC
Labels: bug

**Comment by BlackGrandStyle** [comment] 2021-11-07 12:28
LoL, oks dud, i updated to latest build (only 8 builds - outdated build, of which two more fail, ok)
and it keeps on not working :)

![изображение](https://user-images.githubusercontent.com/88898883/140644826-2320dd3c-06f0-4801-a9f7-76e3bffb6e82.png)

**Comment by NichtStudioCode** [comment] 2021-11-07 12:32
> If it's not caused by the outdated version, you're probably leaving out important information again.

**Comment by BlackGrandStyle** [comment] 2021-11-07 12:37
oh sry and how i can fix him? in the beginning he worked

**Comment by NichtStudioCode** [comment] 2021-11-07 12:45
I don't know why it is not working, but just placing it on a fresh Purpur server without any other plugins works fine.
Did you actually try it without other plugins?
Are there really no errors in the console?
Did you change something in the config?
Is the Mob Killer getting power? (The power cell could be set to input only at the bottom)
Is the area the mobs are in protected?

There are many ways why it doesn't work, including of course a mistake on my part, but the steps to reproduce do not lead to that problem, therefore this bug report is invalid.

**Comment by BlackGrandStyle** [comment] 2021-11-07 13:04
> Did you actually try it without other plugins?
it worked earlier on the same build of plugins, i didn’t add new ones, only removed some old ones and updated protectionstones to 2.9.0

> Are there really no errors in the console?
yep none

> Did you change something in the config?
my config:
https://pastebin.com/wfC7nRhE
my mob killer config:
https://pastebin.com/VSZDWDcm

> Is the Mob Killer getting power? (The power cell could be set to input only at the bottom)
he receives
me and the players have tried all types of cells, wind turbines, solar panels, all cables
it receives but doesn't work

> Is the area the mobs are in protected?
i already wrote that this does not affect in any way
it does not work both in the global region and in individual player regions
global flags:
![изображение](https://user-images.githubusercontent.com/88898883/140646065-f52774d5-088a-4de7-b6ee-837e846432cc.png)

**Comment by NichtStudioCode** [comment] 2021-11-07 13:20
You have selected "This bug also occurs when no other plugins are present." and now you're telling me you've never tried it without other plugins on the server. There is a reason that there are only these two options, you're the one who has to figure out which plugin causes problems (if it's another plugin - which we both don't know because you've never actually tested it).
