### ISSUE TITLE
Nova blocks does not update surroundings when breaked

### ISSUE THREAD

**Issue by Rinuuri** [xenondevs/Nova#306] opened 2023-11-16 12:33 UTC
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova 0.15 alpha 8; Pufferfish 1.20.2 build #32

### Nova Addons and Versions

Machines

### Expected behavior

Blocks around the broken one would be updated to avoid broken block states

### Observed/Actual behavior

The blocks around are not updated, so we can observe block states that should not be in the game

### Steps to reproduce

Install nova and everything, won't go into details, nova and some kind of addon that adds custom blocks, for example machines

Get the block and place it next to the vanilla block that changes block state based on surrounding blocks. Example: oak fence, water

The fence got connected to the placed nova block, water was replaced by the nova block

Break the nova block, now we see that nova block was replaced with air, but fence is still connected to the block the location where nova block previously was, the same case with water, it would not flow to the empty space created when we broke the nova block

### Server log

No errors in the log, i don't think that it would be helpful here

**Comment by NichtStudioCode** [comment] 2023-11-16 14:42
Duplicate of #258

**Closed** 2023-11-16 14:42 UTC
Labels: type: bug, resolution: duplicate
